package com.az7car.watchcat.detection.mod;

import com.az7car.watchcat.core.config.WatchcatConfig;
import com.az7car.watchcat.core.pipeline.AbstractCheck;
import com.az7car.watchcat.detection.base.CheckResult;
import com.az7car.watchcat.detection.base.PlayerData;
import com.az7car.watchcat.util.PacketUtils;
import net.minecraft.network.protocol.Packet;
import net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket;
import net.minecraft.server.level.ServerPlayer;
import org.bukkit.entity.Player;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List;
import java.util.regex.Pattern;

public class BrandDetector extends AbstractCheck {

    private static final List<String> LEGIT_BRANDS = Arrays.asList(
        "vanilla", "fabric", "forge", "quilt", "neoforge",
        "lunar", "badlion", "pvpclient", "optifine", "sodium",
        "iris", "canvas", "indigo", "continuity", "lambdabettergrass",
        "fabrishot", "minihud", "tweakeroo", "malilib", "itemscroller",
        "litematica", "notenoughcrashes", "phosphor", "lithium", "starlight",
        "krypton", "hydrogen", "lazydfu", "smoothboot", "dashloader",
        "entityculling", "betterfpsdist", "immediatelyfast", "cullleaves",
        "reeses_sodium_options", "modmenu", "roughlyenoughitems",
        "appleskin", "jei", "rei", "emi", "wthit", "jade", "xearo",
        "voxelmap", "journeymap", "antighost", "fpsdisplay", "betterpvp",
        "keystrokes", "cpscounter", "neat", "taiga", "btw",
        "clearwater", "presencefootsteps", "soundphysics", "dripstone",
        "fallingleaves", "effective", "adorn", "bewitchment", "patchouli",
        "sereneseasons", "sophisticatedbackpacks", "waystones",
        "supplementaries", "create", "tinkersconstruct", "thermal",
        "mekanism", "botania", "twilightforest", "alexsmobs", "iceandfire",
        "biomesoplenty", "terralith", "simplyswords", "mithril",
        "parry", "weaponmaster", "combatlog", "scoreboard",
        "notenoughanimations", "cameraoverhaul", "bettercombat",
        "playeranimator", "epicfight", "firstperson",
        "feytweaks", "modernfix", "ferritecore", "smoothchunk",
        "cubeswithoutborders", "chunksending", "c2me", "concurrentchunk",
        "verymanyplayers", "spark", "observable", "bdlib", "architectury",
        "clothconfig", "configured", "catalogue", "controlling",
        "inventoryprofilesnext", "recipeessentials", "theoneprobe",
        "hwyla", "waila", "mapfrontiers", "travelerz", "backpacked",
        "travelersbackpack", "comforts", "farmersdelight", "deepresonance",
        "extreme Reactors", "bigreactors", "cyclic", "potionsmaster",
        "apotheosis", "bookshelf", "arsnouveau", "hexcasting", "manaandartifice"
    );

    private static final List<String> BLOCKED_SUBSTRINGS = Arrays.asList(
        "wurst", "meteor", "impact", "aristois", "future", "vape",
        "entropy", "liquidbounce", "sigma", "kami", "troll",
        "huzuni", "nodus", "weepcraft", "vertex", "novoline",
        "venom", "rise", "exhibition", "rhack", "zeroday",
        "nightmare", "panic", "freedom", "redesky", "flux",
        "skidded", "remix", "caveclient", "spiderclient",
        "labyclient", "labymod", "labymodclient", "raccoon",
        "nibiru", "aspect", "crystal", "moonlight", "astraclient",
        "aqua", "smoke", "void", "spook", "spookyclient",
        "sewer", "trashclient", "shidclient", "envyclient",
        "synergy", "blizzard", "fade", "grace", "spirit",
        "cheatbreaker", "rapid", "incognito",
        "wink", "wolfram", "voidclient", "v4lker", "monsterclient",
        "apolloclient", "azury", "blurclient", "blackhole",
        "genesis", "jello", "pomme", "vega", "onion",
        "bacon", "candy", "doge", "dortware", "ethereal",
        "ewy", "fr3nzy", "hackdragon",
        "insanity", "interstellar", "jigsaw", "jigsawnightmare",
        "kaiser", "kevin", "kilo", "lotus", "lvc", "mango",
        "maximus", "myth", "nightx", "niko", "novo",
        "odin", "optihack", "pepsu", "pollo",
        "prestige", "pulsive",
        "raminae", "recode", "rengine", "revamp",
        "satanic", "sb", "scavno", "scum", "sector", "sedoh",
        "seven", "shiro", "silence",
        "skeet", "skidclient", "skidded.cc", "skrec",
        "smoothclient",
        "spookclient", "squad",
        "sunset", "supernova", "supremacy", "sylo", "sythe",
        "trollware",
        "uberware", "valet", "vapeware", "vapium",
        "viper", "vital", "vizzy",
        "vortex", "vykings",
        "warez", "whiteout",
        "xibalba",
        "zeus",
        "zzclient",

        "acolyte", "agriplex", "albion", "alpha", "altair", "andromeda",
        "anomaly", "anti", "april", "aquarius", "arc", "arcadic",
        "arch", "aries", "artemis", "astolfo", "astron", "athena",
        "atlas", "atomic", "austral", "auto", "avalanche", "aventine",
        "avira", "avius", "azrael", "azure",
        "breeze", "breezeclient", "bridge",
        "capri", "carbon", "celsius", "centauri", "centrum", "cerberus",
        "cereal", "cesium", "charlie",
        "clover", "cluster",
        "cobalt", "cobra", "comet", "conquer", "consistency",
        "consomme", "contra", "cookie",
        "corrosion", "cosmos", "crack", "cracked",
        "crash", "creeper",
        "crypt", "cryptic",
        "cyber", "cyclone",
        "dark", "darth", "dawn",
        "decode", "delta",
        "depress", "destroy", "devil",
        "diablo", "diagram",
        "diamond", "digitek", "dirt",
        "dream", "drift",
        "drip", "drown",
        "dynasty",
        "eaa", "eagle", "earth", "eazy",
        "eclipse", "elite",
        "emperor", "enchant",
        "enderman", "endless",
        "enigma",
        "epsilon",
        "erisa",
        "error", "error404",
        "esp", "espex",
        "etb", "etbclient",
        "eureka",
        "event",
        "everest",
        "evolution",
        "execute",
        "executor",
        "exe",
        "exist",
        "exodus",
        "explicit",
        "exploit",
        "exterminate",
        "extinction",
        "extreme",
        "extremespeed",
        "ez",
        "f5", "f7",
        "fallen", "fantasy",
        "fdp", "fdps",
        "feather",
        "festival",
        "final",
        "fire", "fireball",
        "fix",
        "flag", "flags",
        "flare",
        "flash",
        "fleet",
        "flex",
        "flood",
        "fluid",
        "force",
        "forgotten",
        "fortnite",
        "fractal",
        "fragment",
        "frame",
        "freecam",
        "freedom",
        "frog",
        "frost",
        "frozen",
        "fukario",
        "fulcrum",
        "furr",
        "fusion",
        "fwt",
        "galaxy", "gamma",
        "gandalf",
        "garfield",
        "gearbox",
        "gem",
        "gerbil",
        "ghost",
        "ghostware",
        "gister",
        "glacier",
        "gladiator",
        "glisten",
        "globe",
        "gloom",
        "glory",
        "glow",
        "goat",
        "godlike",
        "golem",
        "gosu",
        "grandma",
        "graviton",
        "greif",
        "grief",
        "gringe",
        "gucci",
        "gwen",
        "hadron", "hagrid",
        "hammer",
        "hanna",
        "happy",
        "hard",
        "hark",
        "harmony",
        "hash",
        "haze",
        "hazel",
        "heaven",
        "helios",
        "helix",
        "hell",
        "hero",
        "herobrine",
        "hex",
        "hgod",
        "hibernate",
        "hide",
        "higan",
        "high",
        "hime",
        "hitbox",
        "holy",
        "honor",
        "hook",
        "horizon",
        "horny",
        "hostile",
        "hub",
        "huge",
        "human",
        "hunter",
        "huzuni",
        "hybrid",
        "hydration",
        "hydrogen",
        "hylex",
        "hyper",
        "hypixel",
        "ice", "icetea",
        "ict",
        "ignite",
        "illusion",
        "imagine",
        "immortal",
        "imperial",
        "implant",
        "impossible",
        "inception",
        "inertia",
        "infamous",
        "inferno",
        "infinity",
        "injection",
        "injector",
        "injustice",
        "innocent",
        "inori",
        "insight",
        "insomnia",
        "instinct",
        "interium",
        "intent",
        "internal",
        "interstellar",
        "inventory",
        "invisible",
        "invite",
        "ionic",
        "iris",
        "iron",
        "irrelevant",
        "isaac",
        "isolation",
        "ivory",
        "jackal", "jade",
        "jake",
        "japan",
        "jason",
        "java",
        "jellyfish",
        "jet",
        "jewel",
        "jigsaw",
        "jim",
        "jitter",
        "jni",
        "john",
        "jolt",
        "jordan",
        "jpeg",
        "jupiter",
        "justice",
        "justina",
        "kakashi", "kakarot",
        "kali",
        "karma",
        "kast",
        "katie",
        "katniss",
        "kawaii",
        "kay",
        "kaz",
        "kcd",
        "kebab",
        "keem",
        "kek",
        "kelly",
        "ken",
        "kennedy",
        "kenzie",
        "kepler",
        "kermit",
        "kernel",
        "ketchup",
        "kether",
        "key",
        "keystone",
        "kick",
        "kid",
        "kill",
        "killaura",
        "kilo",
        "kim",
        "kinder",
        "king",
        "kiro",
        "kisman",
        "kiss",
        "kitsune",
        "kitten",
        "kiwi",
        "kjs",
        "klientus",
        "kline",
        "kmack",
        "knight",
        "knockback",
        "knox",
        "kodeh",
        "kohi",
        "konas",
        "kong",
        "korea",
        "kozak",
        "kpopper",
        "krystal",
        "krypton",
        "krystal",
        "kubo",
        "kui",
        "kumori",
        "kuro",
        "kush",
        "kwv",
        "kyle",
        "kyoto",
        "labyrinth",
        "lac",
        "lacerta",
        "ladder",
        "lag",
        "lambda",
        "lame",
        "lamp",
        "land",
        "laos",
        "laptop",
        "larson",
        "laser",
        "last",
        "laughing",
        "launcher",
        "lava",
        "lavender",
        "law",
        "lazarus",
        "lazuli",
        "lazy",
        "lba",
        "ldc",
        "leach",
        "leader",
        "leak",
        "leaked",
        "lease",
        "leather",
        "leaves",
        "led",
        "legend",
        "legendary",
        "legit",
        "legs",
        "leisure",
        "lemon",
        "lengi",
        "leo",
        "leopard",
        "leprechaun",
        "lester",
        "level",
        "lex",
        "lexa",
        "liam",
        "libra",
        "license",
        "lider",
        "life",
        "light",
        "lighting",
        "lightning",
        "lil",
        "lily",
        "lima",
        "limbo",
        "liminal",
        "limit",
        "limited",
        "limp",
        "lincoln",
        "lindsey",
        "line",
        "linear",
        "lined",
        "link",
        "linus",
        "lion",
        "liquid",
        "liquidbounce",
        "liquor",
        "lisa",
        "list",
        "listen",
        "lite",
        "liteloader",
        "lithium",
        "little",
        "live",
        "livid",
        "liz",
        "llama",
        "lnb",
        "loaded",
        "loader",
        "loaf",
        "lobby",
        "local",
        "lock",
        "locked",
        "locus",
        "lode",
        "lodge",
        "lofty",
        "logic",
        "logical",
        "login",
        "logo",
        "loli",
        "lolihunter",
        "lollipop",
        "london",
        "lonely",
        "long",
        "loob",
        "look",
        "loom",
        "loophole",
        "loose",
        "loot",
        "lord",
        "lorenz",
        "lorenzo",
        "lose",
        "lost",
        "loud",
        "lounge",
        "love",
        "lover",
        "low",
        "lowkey",
        "loyal",
        "lspdfr",
        "lua",
        "lubricant",
        "lucas",
        "lucid",
        "lucky",
        "lucy",
        "luffy",
        "luk",
        "luke",
        "lullaby",
        "lulu",
        "luma",
        "luminance",
        "luminous",
        "luna",
        "lunar",
        "lunch",
        "lung",
        "lupus",
        "lurk",
        "luster",
        "lute",
        "lux",
        "luxe",
        "luxury",
        "lycan",
        "lychee",
        "lycoris",
        "lying",
        "lym",
        "lyme",
        "lymph",
        "lynx",
        "lyra",
        "lyric",
        "lyrical",
        "m3",
        "m4",
        "mac",
        "mace",
        "mach",
        "machine",
        "macho",
        "mack",
        "macro",
        "mad",
        "made",
        "madness",
        "maestro",
        "mafia",
        "magic",
        "magician",
        "magnet",
        "magnolia",
        "magnus",
        "maid",
        "maiden",
        "main",
        "maincraft",
        "majestic",
        "major",
        "mak",
        "make",
        "mal",
        "malachi",
        "malcolm",
        "malice",
        "malign",
        "mall",
        "maln",
        "malus",
        "mama",
        "man",
        "manage",
        "manager",
        "mango",
        "manhunt",
        "manifest",
        "manipulate",
        "manny",
        "manson",
        "mantis",
        "manual",
        "maple",
        "marathon",
        "marc",
        "marco",
        "mardi",
        "marg",
        "marina",
        "marion",
        "mark",
        "marker",
        "market",
        "marlin",
        "marmalade",
        "maroon",
        "marriage",
        "mars",
        "marshall",
        "marten",
        "martin",
        "martyr",
        "marvel",
        "marvin",
        "mask",
        "mason",
        "mass",
        "mast",
        "master",
        "mat",
        "match",
        "mate",
        "math",
        "mathew",
        "matrix",
        "matter",
        "mature",
        "maui",
        "maul",
        "mauro",
        "max",
        "maximus",
        "maxine",
        "maximum",
        "maxwell",
        "may",
        "maybe",
        "mayhem",
        "mayo",
        "mayor",
        "maze",
        "mazebolt",
        "mazefall",
        "mazefight",
        "mazegame",
        "mazehub",
        "mazelife",
        "mazemap",
        "mazemc",
        "mazepvp",
        "mazerun",
        "mazesky",
        "mb",
        "mc",
        "mcbe",
        "mcbr",
        "mcc",
        "mcd",
        "mcdonalds",
        "mcf",
        "mcg",
        "mch",
        "mci",
        "mcj",
        "mck",
        "mcl",
        "mcm",
        "mcn",
        "mco",
        "mcp",
        "mcpvp",
        "mcq",
        "mcr",
        "mcs",
        "mct",
        "mcu",
        "mcv",
        "mcw",
        "mcy",
        "mcz",
        "md",
        "mdk",
        "me",
        "meat",
        "mec",
        "mechanic",
        "med",
        "medal",
        "medea",
        "media",
        "medical",
        "medusa",
        "meet",
        "meeting",
        "meg",
        "mega",
        "megan",
        "mel",
        "melody",
        "melon",
        "melt",
        "member",
        "membrane",
        "memento",
        "memo",
        "memoir",
        "memor",
        "memory",
        "memphis",
        "men",
        "mendi",
        "mensa",
        "mental",
        "mentor",
        "menu",
        "meow",
        "merch",
        "merchant",
        "merci",
        "mercury",
        "mercy",
        "mere",
        "merit",
        "merlin",
        "mermaid",
        "merry",
        "mesa",
        "mesh",
        "mess",
        "message",
        "messenger",
        "messy",
        "meta",
        "metal",
        "meteor",
        "meth",
        "method",
        "metro",
        "mew",
        "mex",
        "mexico",
        "miami",
        "mice",
        "michael",
        "michelle",
        "michi",
        "mickey",
        "micro",
        "mid",
        "midas",
        "midget",
        "midnight",
        "midwest",
        "mighty",
        "mike",
        "milan",
        "mild",
        "miles",
        "milf",
        "milk",
        "milky",
        "mill",
        "millennium",
        "miller",
        "milo",
        "milt",
        "mimi",
        "mimic",
        "mind",
        "mine",
        "miner",
        "mineral",
        "miners",
        "minerva",
        "mines",
        "minetweak",
        "mini",
        "mining",
        "minion",
        "minister",
        "mink",
        "minnie",
        "minor",
        "minotaur",
        "mint",
        "minute",
        "mio",
        "miracle",
        "mirage",
        "mirror",
        "mis",
        "misfit",
        "mish",
        "miss",
        "missile",
        "mission",
        "mist",
        "mistake",
        "mister",
        "misty",
        "mit",
        "mitch",
        "mitt",
        "mix",
        "mixed",
        "mixer",
        "mixture",
        "miz",
        "mizu",
        "mk",
        "mlg",
        "mm",
        "mmo",
        "mn",
        "mo",
        "moan",
        "mob",
        "mobbo",
        "mobile",
        "mocha",
        "mock",
        "mode",
        "model",
        "modem",
        "mods",
        "moe",
        "moist",
        "mole",
        "molly",
        "mom",
        "moment",
        "mommy",
        "monarch",
        "monday",
        "money",
        "mong",
        "monic",
        "monika",
        "monitor",
        "monk",
        "monkey",
        "mono",
        "monolith",
        "monopoly",
        "monster",
        "montana",
        "monty",
        "monument",
        "moo",
        "mood",
        "moon",
        "moonlight",
        "moons",
        "moose",
        "mop",
        "moral",
        "moran",
        "more",
        "morgan",
        "morgoth",
        "mori",
        "moria",
        "morning",
        "moro",
        "morph",
        "morphine",
        "moscow",
        "moses",
        "moss",
        "most",
        "mote",
        "mother",
        "motion",
        "motive",
        "motor",
        "motto",
        "mountain",
        "mouse",
        "mouth",
        "move",
        "movement",
        "movie",
        "mow",
        "mower",
        "mp",
        "mr",
        "mrs",
        "ms",
        "mt",
        "mu",
        "much",
        "mud",
        "muffin",
        "mug",
        "mule",
        "mult",
        "multi",
        "multiverse",
        "mum",
        "mumble",
        "mummy",
        "mumu",
        "munch",
        "muppet",
        "murder",
        "murky",
        "murphy",
        "muscle",
        "muse",
        "mushroom",
        "music",
        "musk",
        "must",
        "mustard",
        "mute",
        "mutilate",
        "mutt",
        "mutter",
        "my",
        "mya",
        "myco",
        "myers",
        "mygod",
        "mylife",
        "myname",
        "mynx",
        "myra",
        "myron",
        "myrtle",
        "myself",
        "mystery",
        "mystic",
        "myth",
        "mythic",
        "mythical",
        "mythos",
        "n0",
        "n00b",
        "n1",
        "na",
        "nab",
        "nacho",
        "nada",
        "nade",
        "nadia",
        "nailed",
        "nails",
        "naked",
        "name",
        "nami",
        "namine",
        "nancy",
        "naomi",
        "nap",
        "napa",
        "nape",
        "narc",
        "narcissus",
        "narnia",
        "naruto",
        "nas",
        "nasa",
        "nasty",
        "nat",
        "natal",
        "nathan",
        "nation",
        "native",
        "natural",
        "nature",
        "nausea",
        "navi",
        "navy",
        "nazi",
        "nb",
        "nc",
        "ne",
        "neal",
        "neapolitan",
        "near",
        "neat",
        "nebula",
        "neck",
        "necron",
        "ned",
        "need",
        "needle",
        "needy",
        "neff",
        "neg",
        "negative",
        "neighbor",
        "neil",
        "neko",
        "nemo",
        "neo",
        "neon",
        "nepal",
        "nepgear",
        "nephew",
        "neptune",
        "nerd",
        "nerf",
        "nero",
        "nerve",
        "ness",
        "nest",
        "nestor",
        "net",
        "nether",
        "nethereye",
        "netherite",
        "netherlands",
        "netherrack",
        "nett",
        "network",
        "neu",
        "neural",
        "neuro",
        "neuron",
        "neutral",
        "neutron",
        "nevada",
        "never",
        "new",
        "newlife",
        "newton",
        "next",
        "nexus",
        "nft",
        "ng",
        "ngt",
        "ni",
        "nibble",
        "nic",
        "nice",
        "niche",
        "nick",
        "nicki",
        "nico",
        "niconico",
        "niece",
        "night",
        "nightly",
        "nightmare",
        "nights",
        "nightx",
        "nihil",
        "niko",
        "nil",
        "nile",
        "nim",
        "nimbus",
        "nina",
        "nine",
        "ninety",
        "ninja",
        "nintendo",
        "niobium",
        "nip",
        "nips",
        "nirvana",
        "nis",
        "nisa",
        "nish",
        "nit",
        "nitro",
        "nitrogen",
        "nix",
        "nixon",
        "niz",
        "nizi",
        "nj",
        "nk",
        "nl",
        "nm",
        "nn",
        "no",
        "noah",
        "nob",
        "nobel",
        "noble",
        "nobody",
        "nod",
        "node",
        "nodus",
        "noise",
        "noisy",
        "nolan",
        "nom",
        "nomad",
        "nominal",
        "none",
        "nonsense",
        "noodle",
        "noon",
        "nope",
        "nora",
        "nord",
        "nori",
        "norm",
        "normal",
        "norman",
        "norse",
        "north",
        "norton",
        "nose",
        "nostalgia",
        "not",
        "notch",
        "note",
        "notepad",
        "nothing",
        "notice",
        "nova",
        "novel",
        "november",
        "now",
        "noway",
        "nowhere",
        "nox",
        "noxesium",
        "npc",
        "nrg",
        "ns",
        "nt",
        "nu",
        "nub",
        "nuclear",
        "nude",
        "nugget",
        "null",
        "number",
        "numeric",
        "numeral",
        "nurse",
        "nut",
        "nutella",
        "nuts",
        "nv",
        "nvp",
        "nw",
        "ny",
        "nyan",
        "nyx",
        "oak",
        "oasis",
        "obama",
        "obelisk",
        "oberon",
        "obese",
        "obey",
        "obf",
        "obj",
        "object",
        "oblivion",
        "oboe",
        "obscure",
        "observe",
        "obsession",
        "obsidian",
        "obsolete",
        "obtain",
        "obvious",
        "oc",
        "occult",
        "ocean",
        "ocelot",
        "oct",
        "octopus",
        "odd",
        "odds",
        "odin",
        "odo",
        "odyssey",
        "officer",
        "official",
        "offline",
        "offspring",
        "often",
        "oh",
        "ohio",
        "oil",
        "ok",
        "okay",
        "old",
        "oldie",
        "oliver",
        "ollie",
        "olympic",
        "omega",
        "omen",
        "omg",
        "omni",
        "omnipotent",
        "on",
        "once",
        "one",
        "onion",
        "online",
        "only",
        "onset",
        "onyx",
        "oob",
        "ooze",
        "op",
        "open",
        "opera",
        "operate",
        "opium",
        "opt",
        "optic",
        "optimal",
        "optimum",
        "option",
        "optix",
        "opus",
        "or",
        "oracle",
        "orange",
        "orbit",
        "orca",
        "orchid",
        "order",
        "ore",
        "oreo",
        "org",
        "organ",
        "origin",
        "original",
        "orion",
        "ornament",
        "orphan",
        "oscar",
        "oscillate",
        "otaku",
        "other",
        "otter",
        "otto",
        "ou",
        "ought",
        "ounce",
        "our",
        "out",
        "outcast",
        "outfit",
        "outlaw",
        "outline",
        "output",
        "outrun",
        "outset",
        "outside",
        "outwit",
        "oval",
        "oven",
        "over",
        "overcast",
        "overcome",
        "overdo",
        "overflow",
        "overhaul",
        "overlay",
        "overload",
        "overnight",
        "override",
        "oversight",
        "overwatch",
        "owe",
        "owl",
        "own",
        "owner",
        "ox",
        "oxford",
        "oxide",
        "oxygen",
        "p0",
        "pa",
        "pace",
        "pacific",
        "pack",
        "package",
        "packer",
        "packet",
        "pact",
        "pad",
        "paddle",
        "page",
        "pager",
        "paint",
        "pair",
        "pal",
        "palace",
        "pale",
        "palm",
        "pan",
        "pand",
        "panda",
        "pane",
        "panel",
        "panic",
        "panorama",
        "pant",
        "pants",
        "papa",
        "paper",
        "par",
        "parade",
        "paradise",
        "parallel",
        "paranoid",
        "parasite",
        "parch",
        "parent",
        "paris",
        "park",
        "parkour",
        "parrot",
        "part",
        "particle",
        "party",
        "pass",
        "passion",
        "passive",
        "passport",
        "password",
        "paste",
        "pat",
        "patch",
        "patent",
        "path",
        "patience",
        "patient",
        "patrol",
        "pattern",
        "paul",
        "pause",
        "pave",
        "paw",
        "pawn",
        "pay",
        "payment",
        "pb",
        "pc",
        "pd",
        "pe",
        "peace",
        "peach",
        "peak",
        "peanut",
        "pearl",
        "pebble",
        "peculiar",
        "pedro",
        "peel",
        "peer",
        "pegasus",
        "pellet",
        "pen",
        "penalty",
        "pencil",
        "pend",
        "pending",
        "penguin",
        "penis",
        "penny",
        "pension",
        "pent",
        "peony",
        "people",
        "pepper",
        "per",
        "perch",
        "perfect",
        "perform",
        "perfume",
        "perhaps",
        "peridot",
        "perish",
        "perk",
        "perl",
        "perm",
        "permanent",
        "permit",
        "perry",
        "persist",
        "person",
        "pet",
        "petal",
        "pete",
        "peter",
        "petra",
        "petrol",
        "pew",
        "pf",
        "pg",
        "ph",
        "phantom",
        "phase",
        "phd",
        "phenom",
        "phi",
        "phil",
        "phobia",
        "phone",
        "photo",
        "phrase",
        "physical",
        "pi",
        "piano",
        "pic",
        "pick",
        "pickle",
        "pico",
        "picture",
        "pie",
        "piece",
        "pier",
        "pierre",
        "pig",
        "pigeon",
        "piggy",
        "pike",
        "pile",
        "pill",
        "pilot",
        "pin",
        "pinch",
        "pine",
        "ping",
        "pink",
        "pint",
        "pioneer",
        "pipe",
        "pirate",
        "piss",
        "pistol",
        "pit",
        "pitch",
        "pixel",
        "pixie",
        "pizza",
        "pj",
        "pk",
        "pl",
        "place",
        "plague",
        "plain",
        "plan",
        "plane",
        "planet",
        "plank",
        "plant",
        "plastic",
        "plate",
        "plat",
        "play",
        "player",
        "playground",
        "playlist",
        "playsound",
        "plaza",
        "plead",
        "pleasant",
        "please",
        "pleasure",
        "pledge",
        "plenty",
        "plot",
        "plow",
        "plum",
        "plume",
        "plunder",
        "pluto",
        "ply",
        "pm",
        "pn",
        "po",
        "pocket",
        "pod",
        "poem",
        "poet",
        "poetry",
        "point",
        "poison",
        "poke",
        "polar",
        "pole",
        "police",
        "policy",
        "polish",
        "polite",
        "polo",
        "poly",
        "pomf",
        "pomp",
        "poncho",
        "pond",
        "pony",
        "pool",
        "poor",
        "pop",
        "pope",
        "poppy",
        "popular",
        "porch",
        "pork",
        "port",
        "portal",
        "porto",
        "pose",
        "posh",
        "position",
        "positive",
        "possess",
        "post",
        "postal",
        "pot",
        "potato",
        "potential",
        "potion",
        "pound",
        "pour",
        "powder",
        "power",
        "pp",
        "pr",
        "practical",
        "praise",
        "prank",
        "pray",
        "pre",
        "precious",
        "predator",
        "prefer",
        "premier",
        "premium",
        "prepare",
        "present",
        "preset",
        "press",
        "pressure",
        "prestige",
        "pretty",
        "prevent",
        "preview",
        "price",
        "pride",
        "prime",
        "prince",
        "print",
        "prior",
        "prism",
        "prison",
        "private",
        "prize",
        "pro",
        "probe",
        "problem",
        "proceed",
        "process",
        "prodigy",
        "produce",
        "product",
        "profil",
        "profit",
        "program",
        "project",
        "promise",
        "promo",
        "proof",
        "prop",
        "proper",
        "prophet",
        "proposal",
        "prosper",
        "protect",
        "protein",
        "protest",
        "proud",
        "prove",
        "proxy",
        "prune",
        "ps",
        "psi",
        "psycho",
        "pt",
        "pub",
        "public",
        "puck",
        "puff",
        "pull",
        "pulse",
        "pump",
        "pumpkin",
        "punch",
        "punk",
        "pupil",
        "puppet",
        "puppy",
        "pure",
        "purple",
        "purpose",
        "purr",
        "purse",
        "push",
        "put",
        "puzzle",
        "pv",
        "pvp",
        "pw",
        "py",
        "pyramid",
        "python"
    );

    private static final List<String> MAJOR_CHEAT_BRANDS = Arrays.asList(
        "vape", "v4", "vape.rip", "vapeclient",
        "meteor", "meteorclient", "meteor-client",
        "wurst", "wurstclient", "wurst-client",
        "impact", "impactclient", "impact-client",
        "aristois", "aristoisclient",
        "future", "futureclient",
        "liquidbounce", "liquid-bounce", "liquidbounce-client",
        "sigma5", "sigma6", "sigmaclient",
        "kami", "kamiblue",
        "inertia", "inertiaclient",
        "zero", "zeroday",
        "novoline", "novolineclient",
        "blue", "blueclient",
        "rise", "riseclient",
        "exhibition", "exhibitionclient",
        "raven", "ravenclient", "raven-b",
        "simply", "simplyhax",
        "phobos", "phobosclient",
        "rusherhack", "rusherhack-client",
        "salhack", "salhack-client",
        "kilo", "kilohack",
        "monster", "monsterclient",
        "gamesense", "gamesenseclient",
        "advancedwars", "advancedwars-client",
        "nightx", "nightx-client",
        "crystallinqz",
        "moonlight", "moonlight-client",
        "espex", "espexclient",
        "void", "voidclient", "void-client",
        "mio", "mioclient",
        "summit", "summitclient",
        "matrex", "matrexclient",
        "mango", "mangoclient",
        "slow", "slowclient",
        "aqua", "aquaclient",
        "weepcraft", "weep-craft",
        "nodus", "nodusclient",
        "huzuni", "huzuniclient",
        "cubecraft", "cubecraft-client",
        "atom", "atomclient",
        "clicker", "autoclicker",
        "autoarmor", "autototem",
        "antikb", "antiknockback",
        "killaura", "aura",
        "aimassist", "aimbot",
        "esp", "wallhack", "wallhack-client",
        "xray", "xray-client",
        "freecam", "free-cam",
        "scaffold", "tower",
        "nofall", "nofalldamage",
        "velocity", "antivelocity",
        "criticals", "autocriticals",
        "cheatbreaker",
        "racoon", "raccoon",
        "kisman", "kismanclient",
        "o7", "o7client",
        "vapium", "vapium-client",
        "useless", "uselessclient",
        "dotgod", "dotgodclient",
        "pyro", "pyroclient",
        "nan0", "nan0-client",
        "sketch", "sketchclient",
        "candy", "candyclient",
        "opium", "opiumclient",
        "azury", "azuryclient",
        "blizzard", "blizzardclient",
        "azure", "azureclient",
        "sly", "slyclient",
        "ryuk", "ryukclient"
    );

    private static final List<String> BLOCKED_EXACT_BRANDS = Arrays.asList(
        "vape", "v4", "wurst", "meteor", "impact", "aristois",
        "future", "liquidbounce", "sigma", "novoline", "rise",
        "exhibition", "inertia", "phobos", "rusherhack", "salhack",
        "gamesense", "raven", "kilo", "weepcraft", "nodus", "huzuni",
        "cock", "fuck", "shit", "bitch", "nigger", "kike",
        "faggot", "nazi", "kkk", "dick", "pussy", "asshole",
        "cunt", "whore", "slut", "retard", "mongoloid",
        "nigga", "spic", "chink", "gook", "wop", "kraut"
    );

    private static final Pattern OBFUSCATED_PATTERN = Pattern.compile(
        "^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])[a-zA-Z0-9]{20,}$");

    private static final Pattern SUSPICIOUS_PAYLOAD_PATTERN = Pattern.compile(
        "^[a-zA-Z0-9]{8,}$");

    private static final List<Pattern> REGEX_BLOCKED = Arrays.asList(
        Pattern.compile(".*(cheat|hack|client|ware|bypass|exploit|crack|mod).*", Pattern.CASE_INSENSITIVE),
        Pattern.compile(".*(v[0-9]+|r[0-9]+|b[0-9]+|build[0-9]+).*", Pattern.CASE_INSENSITIVE),
        Pattern.compile(".*\\d{10,}.*"),
        Pattern.compile(".*(leaked|private|premium|cracked|free).*", Pattern.CASE_INSENSITIVE)
    );

    public BrandDetector(WatchcatConfig config) {
        super("BrandDetector", "mod",
            config.getCheckWeight("mod.brand"),
            config.isCheckEnabled("mod.brand"));
    }

    @Override
    public CheckResult processSync(Player player, PlayerData data, Packet<?> packet, ServerPlayer nmsPlayer) {
        if (!(packet instanceof ServerboundCustomPayloadPacket)) return CheckResult.PASS;
        String channel = PacketUtils.getPayloadChannel(packet);
        if (channel == null) return CheckResult.PASS;
        if (channel.equals("minecraft:brand") || channel.equals("MC|Brand")) {
            byte[] payload = PacketUtils.getPayloadData(packet);
            if (payload == null) return CheckResult.PASS;
            String brand = new String(payload, StandardCharsets.UTF_8).toLowerCase().trim();
            data.setClientBrand(brand);

            if (checkCheatBrand(brand)) {
                return CheckResult.CANCELLED;
            }
        }
        return CheckResult.PASS;
    }

    @Override
    public CheckResult process(Player player, PlayerData data, Packet<?> packet, ServerPlayer nmsPlayer) {
        if (!(packet instanceof ServerboundCustomPayloadPacket)) return CheckResult.PASS;

        String channel = PacketUtils.getPayloadChannel(packet);
        if (channel == null) return CheckResult.PASS;

        if (channel.equals("minecraft:brand") || channel.equals("MC|Brand")) {
            byte[] payload = PacketUtils.getPayloadData(packet);
            if (payload == null) return CheckResult.PASS;

            String brand = new String(payload, StandardCharsets.UTF_8).toLowerCase().trim();
            data.setClientBrand(brand);

            if (checkCheatBrand(brand)) {
                return CheckResult.FLAG;
            }

            boolean isKnown = false;
            for (String legit : LEGIT_BRANDS) {
                if (brand.contains(legit)) {
                    isKnown = true;
                    break;
                }
            }

            if (!isKnown && brand.length() > 2) {
                return CheckResult.FLAG;
            }
        }

        return CheckResult.PASS;
    }

    private boolean checkCheatBrand(String brand) {
        for (String blocked : BLOCKED_SUBSTRINGS) {
            if (brand.contains(blocked)) {
                return true;
            }
        }

        for (String major : MAJOR_CHEAT_BRANDS) {
            if (brand.contains(major)) {
                return true;
            }
        }

        for (String exact : BLOCKED_EXACT_BRANDS) {
            if (brand.equals(exact)) {
                return true;
            }
        }

        for (Pattern p : REGEX_BLOCKED) {
            if (p.matcher(brand).matches()) {
                return true;
            }
        }

        if (OBFUSCATED_PATTERN.matcher(brand).matches()) {
            return true;
        }

        if (brand.length() > 3 && SUSPICIOUS_PAYLOAD_PATTERN.matcher(brand).matches()) {
            int digitCount = 0;
            for (char c : brand.toCharArray()) {
                if (Character.isDigit(c)) digitCount++;
            }
            if ((double) digitCount / brand.length() > 0.3) {
                return true;
            }
        }

        return false;
    }
}
